import React, { useState, useMemo } from "react";
import { 
  ClipboardList, Sparkles, Target, Shield, Rocket, Loader2, Download, 
  CheckCircle2, ChevronRight, BarChart, Globe, Search, Filter, Layers, 
  Sprout, Apple, Milk, Coffee, Utensils, ShoppingBag, Heart, Smile, 
  Activity, ArrowRight, BookOpen, RefreshCw, Check
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { BusinessPlan } from "../../types";
import { generateBusinessPlan } from "../../services/geminiService";
import { ORGANIC_BUSINESS_TEMPLATES, OrganicBusinessTemplate } from "../data/organicBusinessTemplates";
import { cn } from "../lib/utils";
import jsPDF from "jspdf";

interface OrganicBusinessPlanProps {
  apiKey?: string;
}

type TemplateCategory = "All" | "Farming & Agriculture" | "Food & Hospitality" | "CPG & Retail" | "Professional & Digital Services";

export const OrganicBusinessPlan: React.FC<OrganicBusinessPlanProps> = ({ apiKey }) => {
  const [businessName, setBusinessName] = useState("");
  const [niche, setNiche] = useState("");
  const [goals, setGoals] = useState("");
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<BusinessPlan | null>(null);
  const [error, setError] = useState<string | null>(null);
  
  // Template Explorer State
  const [selectedCategory, setSelectedCategory] = useState<TemplateCategory>("All");
  const [searchQuery, setSearchQuery] = useState("");
  const [activeLoadedTemplateId, setActiveLoadedTemplateId] = useState<string | null>(null);

  const categories: TemplateCategory[] = [
    "All",
    "Farming & Agriculture",
    "Food & Hospitality",
    "CPG & Retail",
    "Professional & Digital Services"
  ];

  const filteredTemplates = useMemo(() => {
    return ORGANIC_BUSINESS_TEMPLATES.filter(tpl => {
      const matchesCat = selectedCategory === "All" || tpl.category === selectedCategory;
      const q = searchQuery.toLowerCase().trim();
      const matchesSearch = !q || 
        tpl.title.toLowerCase().includes(q) ||
        tpl.businessName.toLowerCase().includes(q) ||
        tpl.niche.toLowerCase().includes(q) ||
        tpl.summary.toLowerCase().includes(q) ||
        tpl.keyCertifications.some(c => c.toLowerCase().includes(q));
      return matchesCat && matchesSearch;
    });
  }, [selectedCategory, searchQuery]);

  const handleApplyTemplateToForm = (template: OrganicBusinessTemplate) => {
    setBusinessName(template.businessName);
    setNiche(template.niche);
    setGoals(template.goals);
    setActiveLoadedTemplateId(template.id);
    
    // Scroll smoothly to form
    const formEl = document.getElementById("plan-generator-form");
    if (formEl) {
      formEl.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  };

  const handleInstantViewPlan = (template: OrganicBusinessTemplate) => {
    setPlan(template.defaultPlan);
    setActiveLoadedTemplateId(template.id);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handleGenerate = async () => {
    if (!businessName || !niche) return;
    setLoading(true);
    setError(null);
    try {
      const result = await generateBusinessPlan({ businessName, niche, goals }, apiKey);
      setPlan(result);
      window.scrollTo({ top: 0, behavior: "smooth" });
    } catch (err: any) {
      setError(err.message || "Failed to generate business plan");
    } finally {
      setLoading(false);
    }
  };

  const exportToPDF = () => {
    if (!plan) return;
    const doc = new jsPDF();
    const margin = 20;
    let y = 20;

    const addText = (text: string, size: number, isBold = false) => {
      doc.setFontSize(size);
      doc.setFont("helvetica", isBold ? "bold" : "normal");
      const lines = doc.splitTextToSize(text, 170);
      doc.text(lines, margin, y);
      y += (lines.length * (size / 2)) + 5;
      if (y > 280) {
        doc.addPage();
        y = 20;
      }
    };

    addText("Organic Business Plan: " + plan.businessName, 22, true);
    addText("Generated by Organic Bob - SearchForOrganics.com", 10);
    y += 10;

    addText("Vision", 16, true);
    addText(plan.vision, 12);
    
    addText("Target Market", 16, true);
    addText(plan.targetMarket, 12);

    addText("Revenue Model", 16, true);
    addText(plan.revenueModel, 12);

    addText("Supply Chain Strategy", 16, true);
    addText(plan.supplyChainStrategy, 12);

    addText("Purity Commitment", 16, true);
    addText(plan.purityCommitment, 12);

    addText("Marketing Approach", 16, true);
    addText(plan.marketingApproach, 12);

    addText("Financial Projections", 16, true);
    addText(plan.financialProjections, 12);

    addText("Risk Mitigation", 16, true);
    addText(plan.riskMitigation, 12);

    addText("Next Steps", 16, true);
    plan.nextSteps.forEach(step => addText("- " + step, 12));

    doc.save(`${plan.businessName.replace(/\s+/g, '_')}_Business_Plan.pdf`);
  };

  const exportToHTML = () => {
    if (!plan) return;
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${plan.businessName} - Organic Business Plan</title>
        <style>
          body { font-family: sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: auto; padding: 40px; }
          h1 { color: #047857; border-bottom: 2px solid #047857; padding-bottom: 10px; }
          h2 { color: #111827; margin-top: 30px; }
          .section { margin-bottom: 40px; }
          .footer { margin-top: 60px; font-size: 0.8em; color: #666; border-top: 1px solid #eee; padding-top: 20px; }
        </style>
      </head>
      <body>
        <h1>Organic Business Plan: ${plan.businessName}</h1>
        <p>Generated by <strong>Organic Bob</strong> for SearchForOrganics.com</p>

        <div class="section">
          <h2>Vision</h2>
          <p>${plan.vision}</p>
        </div>

        <div class="section">
          <h2>Target Market</h2>
          <p>${plan.targetMarket}</p>
        </div>

        <div class="section">
          <h2>Revenue Model</h2>
          <p>${plan.revenueModel}</p>
        </div>

        <div class="section">
          <h2>Supply Chain Strategy</h2>
          <p>${plan.supplyChainStrategy}</p>
        </div>

        <div class="section">
          <h2>Purity Commitment</h2>
          <p>${plan.purityCommitment}</p>
        </div>

        <div class="section">
          <h2>Marketing Approach</h2>
          <p>${plan.marketingApproach}</p>
        </div>

        <div class="section">
          <h2>Financial Projections</h2>
          <p>${plan.financialProjections}</p>
        </div>

        <div class="section">
          <h2>Risk Mitigation</h2>
          <p>${plan.riskMitigation}</p>
        </div>

        <div class="section">
          <h2>Next Steps</h2>
          <ul>
            ${plan.nextSteps.map(step => `<li>${step}</li>`).join('')}
          </ul>
        </div>

        <div class="footer">
          &copy; ${new Date().getFullYear()} SearchForOrganics.com - Guided by Organic Integrity.
        </div>
      </body>
      </html>
    `;
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${plan.businessName.replace(/\s+/g, '_')}_Business_Plan.html`;
    a.click();
  };

  const renderIcon = (type: string) => {
    switch (type) {
      case "Sprout": return <Sprout className="w-5 h-5" />;
      case "Apple": return <Apple className="w-5 h-5" />;
      case "Milk": return <Milk className="w-5 h-5" />;
      case "Coffee": return <Coffee className="w-5 h-5" />;
      case "Utensils": return <Utensils className="w-5 h-5" />;
      case "ShoppingBag": return <ShoppingBag className="w-5 h-5" />;
      case "Heart": return <Heart className="w-5 h-5" />;
      case "Smile": return <Smile className="w-5 h-5" />;
      case "BarChart": return <BarChart className="w-5 h-5" />;
      case "Shield": return <Shield className="w-5 h-5" />;
      default: return <Sparkles className="w-5 h-5" />;
    }
  };

  return (
    <div className="max-w-7xl mx-auto space-y-16 pb-24 px-4 sm:px-6">
      {/* Header */}
      <div className="text-center space-y-4 max-w-3xl mx-auto">
        <div className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-50 text-emerald-800 rounded-full text-[10px] font-black uppercase tracking-widest border border-emerald-100 shadow-sm">
          <ClipboardList className="w-4 h-4 text-emerald-600" />
          Organic Venture Builder & Template Hub
        </div>
        <h2 className="text-4xl md:text-5xl font-black text-gray-900 tracking-tight leading-none uppercase italic">
          Organic Business Plan Generator
        </h2>
        <p className="text-base md:text-lg text-gray-600 leading-relaxed font-medium">
          Architect an ethical, profitable organic enterprise. Choose from <span className="font-bold text-emerald-700">20+ certified industry templates</span> or generate a custom AI blueprint with Organic Bob.
        </p>
      </div>

      {/* Plan View Mode (When a plan is active) */}
      {plan ? (
        <div className="space-y-12">
          {/* Active Plan Banner Bar */}
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4 p-6 bg-emerald-950 text-white rounded-3xl border border-emerald-800 shadow-xl">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 rounded-2xl bg-emerald-800 flex items-center justify-center text-emerald-300 flex-shrink-0">
                <Rocket className="w-6 h-6" />
              </div>
              <div>
                <p className="text-[10px] font-black text-emerald-400 uppercase tracking-widest">Active Blueprint</p>
                <h3 className="text-xl md:text-2xl font-black uppercase tracking-tight">{plan.businessName}</h3>
              </div>
            </div>
            <div className="flex items-center gap-3 w-full sm:w-auto">
              <button
                onClick={exportToPDF}
                className="flex-1 sm:flex-initial flex items-center justify-center gap-2 px-5 py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl text-xs font-black uppercase tracking-wider transition-all shadow-md active:scale-95"
              >
                <Download className="w-4 h-4" />
                PDF
              </button>
              <button
                onClick={exportToHTML}
                className="flex-1 sm:flex-initial flex items-center justify-center gap-2 px-5 py-2.5 bg-white/10 hover:bg-white/20 text-white border border-white/20 rounded-xl text-xs font-black uppercase tracking-wider transition-all active:scale-95"
              >
                <Globe className="w-4 h-4" />
                HTML
              </button>
              <button
                onClick={() => {
                  setPlan(null);
                  window.scrollTo({ top: 0, behavior: "smooth" });
                }}
                className="flex-1 sm:flex-initial flex items-center justify-center gap-2 px-5 py-2.5 bg-gray-800 hover:bg-gray-700 text-gray-300 rounded-xl text-xs font-black uppercase tracking-wider transition-all active:scale-95"
              >
                <RefreshCw className="w-4 h-4" />
                New Plan
              </button>
            </div>
          </div>

          {/* Grid Layout of Plan Content */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Sidebar Overview */}
            <div className="lg:col-span-1 space-y-6">
              <div className="bg-white rounded-3xl p-8 border border-gray-100 shadow-xl space-y-6">
                <div className="space-y-2">
                  <p className="text-emerald-700 font-black uppercase tracking-widest text-[10px]">Venture Details</p>
                  <h4 className="text-2xl font-black text-gray-900 uppercase italic">{plan.businessName}</h4>
                </div>

                <div className="p-5 bg-emerald-50 rounded-2xl border border-emerald-100 space-y-3">
                  <div className="flex items-center gap-2 text-emerald-800">
                    <Shield className="w-4 h-4 text-emerald-600" />
                    <span className="font-black text-[10px] uppercase tracking-widest">Purity Protocol</span>
                  </div>
                  <p className="text-gray-700 text-xs leading-relaxed italic font-medium">
                    "{plan.purityCommitment}"
                  </p>
                </div>

                <div className="space-y-3 pt-2">
                  <button 
                    onClick={exportToPDF}
                    className="w-full flex items-center justify-center gap-2 py-3.5 bg-emerald-900 text-white rounded-2xl text-xs font-black uppercase tracking-widest hover:bg-emerald-800 transition-all shadow-md"
                  >
                    <Download className="w-4 h-4" />
                    Download Official PDF
                  </button>
                  <button 
                    onClick={exportToHTML}
                    className="w-full flex items-center justify-center gap-2 py-3.5 bg-gray-50 text-gray-700 border border-gray-200 rounded-2xl text-xs font-black uppercase tracking-widest hover:bg-gray-100 transition-all"
                  >
                    <Globe className="w-4 h-4" />
                    Export Clean HTML
                  </button>
                </div>
              </div>

              <div className="bg-emerald-900 text-white rounded-3xl p-8 border border-emerald-800 shadow-xl space-y-4">
                <div className="flex items-center gap-2 text-emerald-400">
                  <Target className="w-5 h-5" />
                  <h4 className="font-black text-xs uppercase tracking-widest">Bob's Strategic Rule</h4>
                </div>
                <p className="text-xs text-emerald-100/90 leading-relaxed italic">
                  "In certified organic enterprise, authentic supply chain traceability is not an overhead expense — it is your most defensible competitive moat. Never compromise on soil integrity."
                </p>
              </div>
            </div>

            {/* Main Plan Sections */}
            <div className="lg:col-span-2 space-y-6">
              {[
                { title: "Vision & Philosophy", icon: <Globe className="w-5 h-5" />, content: plan.vision },
                { title: "Target Audience & Demographics", icon: <Target className="w-5 h-5" />, content: plan.targetMarket },
                { title: "Revenue Model & Unit Economics", icon: <BarChart className="w-5 h-5" />, content: plan.revenueModel },
                { title: "Supply Chain & Farm Sourcing", icon: <Sprout className="w-5 h-5" />, content: plan.supplyChainStrategy },
                { title: "Marketing Strategy & Brand Growth", icon: <Sparkles className="w-5 h-5" />, content: plan.marketingApproach },
                { title: "Financial Forecast & Scalability", icon: <ClipboardList className="w-5 h-5" />, content: plan.financialProjections },
                { title: "Risk Mitigation & Compliance", icon: <Shield className="w-5 h-5" />, content: plan.riskMitigation },
              ].map((section, i) => (
                <motion.div 
                  key={i}
                  initial={{ opacity: 0, y: 15 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.05 }}
                  className="bg-white rounded-3xl border border-gray-100 shadow-lg p-8 space-y-4"
                >
                  <div className="flex items-center gap-3">
                    <div className="p-2.5 bg-emerald-50 rounded-xl text-emerald-700">
                      {section.icon}
                    </div>
                    <h4 className="text-xl font-black text-gray-900 uppercase tracking-tight">{section.title}</h4>
                  </div>
                  <p className="text-sm md:text-base text-gray-600 leading-relaxed font-medium">
                    {section.content}
                  </p>
                </motion.div>
              ))}

              {/* Execution Next Steps */}
              <motion.div 
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.4 }}
                className="bg-gray-900 rounded-3xl p-8 text-white space-y-6 shadow-xl"
              >
                <div className="flex items-center gap-3">
                  <div className="p-2.5 bg-emerald-500 rounded-xl text-white">
                    <ChevronRight className="w-5 h-5" />
                  </div>
                  <h4 className="text-xl font-black uppercase tracking-tight italic">Execution Phase: 90-Day Milestones</h4>
                </div>
                <div className="space-y-3">
                  {plan.nextSteps.map((step, i) => (
                    <div key={i} className="flex items-start gap-3 p-4 bg-white/5 rounded-2xl border border-white/10 group hover:bg-white/10 transition-all">
                      <CheckCircle2 className="w-5 h-5 text-emerald-400 flex-shrink-0 mt-0.5" />
                      <p className="text-sm font-medium text-gray-200">{step}</p>
                    </div>
                  ))}
                </div>
              </motion.div>
            </div>
          </div>
        </div>
      ) : (
        /* Generator & Templates Explorer */
        <div className="space-y-16">
          {/* AI Custom Builder Form */}
          <div id="plan-generator-form" className="bg-white rounded-[2.5rem] border border-gray-100 shadow-2xl p-8 md:p-12 max-w-3xl mx-auto space-y-8">
            <div className="flex items-center gap-4 border-b border-gray-100 pb-6">
              <div className="w-14 h-14 bg-emerald-50 rounded-2xl flex items-center justify-center text-emerald-600 flex-shrink-0">
                <Rocket className="w-7 h-7" />
              </div>
              <div>
                <h3 className="text-2xl font-black text-gray-900 uppercase italic">Custom Blueprint Generator</h3>
                <p className="text-xs font-bold text-gray-500 uppercase tracking-widest mt-1">
                  Fill in your concept or select one of the 20+ templates below
                </p>
              </div>
            </div>

            {error && (
              <div className="p-4 bg-red-50 text-red-700 text-xs rounded-2xl border border-red-100 font-bold">
                {error}
              </div>
            )}

            <div className="space-y-6">
              <div className="space-y-2">
                <label className="text-[10px] font-black text-gray-400 uppercase tracking-widest ml-1">Proposed Brand / Venture Name</label>
                <input
                  type="text"
                  placeholder="e.g., Wild Harvest Micro-Apothecary"
                  className="w-full px-5 py-4 bg-gray-50 border border-gray-200 rounded-2xl focus:ring-4 focus:ring-emerald-500/10 focus:border-emerald-500 outline-none transition-all font-bold text-base text-gray-800"
                  value={businessName}
                  onChange={(e) => setBusinessName(e.target.value)}
                />
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-black text-gray-400 uppercase tracking-widest ml-1">Organic Venture Niche & Core Produce / Service</label>
                <input
                  type="text"
                  placeholder="e.g., Certified organic sourdough micro-bakery, regenerative berry orchard..."
                  className="w-full px-5 py-4 bg-gray-50 border border-gray-200 rounded-2xl focus:ring-4 focus:ring-emerald-500/10 focus:border-emerald-500 outline-none transition-all font-bold text-base text-gray-800"
                  value={niche}
                  onChange={(e) => setNiche(e.target.value)}
                />
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-black text-gray-400 uppercase tracking-widest ml-1">Primary Growth & Revenue Goals (Optional)</label>
                <textarea
                  placeholder="e.g., Achieve $25k MRR within 12 months with 100% soil-to-shelf transparency and direct CSA subscriptions..."
                  className="w-full px-5 py-4 bg-gray-50 border border-gray-200 rounded-2xl focus:ring-4 focus:ring-emerald-500/10 focus:border-emerald-500 outline-none transition-all font-bold text-sm text-gray-800 min-h-[100px]"
                  value={goals}
                  onChange={(e) => setGoals(e.target.value)}
                />
              </div>
            </div>

            <button
              onClick={handleGenerate}
              disabled={loading || !businessName || !niche}
              className="w-full py-5 bg-emerald-900 hover:bg-emerald-800 text-white rounded-2xl font-black text-base md:text-lg disabled:opacity-50 transition-all shadow-xl flex items-center justify-center gap-3 uppercase tracking-widest active:scale-95"
            >
              {loading ? (
                <>
                  <Loader2 className="w-6 h-6 animate-spin text-emerald-400" />
                  Architecting Your Custom Plan...
                </>
              ) : (
                <>
                  <Sparkles className="w-6 h-6 text-emerald-400" />
                  Generate AI Organic Blueprint
                </>
              )}
            </button>
          </div>

          {/* 20+ Template Catalog Section */}
          <div className="space-y-8">
            <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-gray-200 pb-8">
              <div className="space-y-2">
                <div className="flex items-center gap-2 text-emerald-700 text-xs font-black uppercase tracking-widest">
                  <Layers className="w-4 h-4" />
                  Starter Blueprints ({ORGANIC_BUSINESS_TEMPLATES.length} Available)
                </div>
                <h3 className="text-3xl font-black text-gray-900 uppercase italic">
                  Explore Ready-to-Use Business Templates
                </h3>
                <p className="text-sm text-gray-600 max-w-xl">
                  Select any organic business model from farm-to-table restaurants to SEO practices. Load into the AI generator or view the complete plan instantly.
                </p>
              </div>

              {/* Search Bar */}
              <div className="relative w-full md:w-80">
                <Search className="w-4 h-4 absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" />
                <input
                  type="text"
                  placeholder="Filter templates (e.g. SEO, juice, farm)..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full pl-11 pr-4 py-3 bg-white border border-gray-200 rounded-2xl text-xs font-bold text-gray-800 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none shadow-sm"
                />
              </div>
            </div>

            {/* Category Filter Pills */}
            <div className="flex flex-wrap items-center gap-2">
              {categories.map((cat) => (
                <button
                  key={cat}
                  onClick={() => setSelectedCategory(cat)}
                  className={cn(
                    "px-4 py-2 rounded-xl text-xs font-black uppercase tracking-wider transition-all border shadow-sm active:scale-95",
                    selectedCategory === cat
                      ? "bg-emerald-800 text-white border-emerald-800"
                      : "bg-white text-gray-600 border-gray-200 hover:border-emerald-600 hover:text-emerald-700"
                  )}
                >
                  {cat} {cat === "All" && `(${ORGANIC_BUSINESS_TEMPLATES.length})`}
                </button>
              ))}
            </div>

            {/* Templates Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredTemplates.map((template) => (
                <div
                  key={template.id}
                  className="bg-white rounded-3xl border border-gray-200 hover:border-emerald-500/50 shadow-md hover:shadow-xl transition-all p-7 flex flex-col justify-between space-y-6 group"
                >
                  {/* Top Details */}
                  <div className="space-y-4">
                    <div className="flex items-center justify-between gap-2">
                      <span className="px-3 py-1 bg-emerald-50 text-emerald-800 rounded-lg text-[9px] font-black uppercase tracking-widest border border-emerald-100">
                        {template.category}
                      </span>
                      <div className="w-8 h-8 rounded-xl bg-gray-50 flex items-center justify-center text-emerald-700 group-hover:bg-emerald-700 group-hover:text-white transition-colors">
                        {renderIcon(template.iconType)}
                      </div>
                    </div>

                    <div>
                      <h4 className="text-lg font-black text-gray-900 group-hover:text-emerald-800 transition-colors leading-snug">
                        {template.title}
                      </h4>
                      <p className="text-xs font-bold text-gray-500 italic mt-0.5">
                        "{template.businessName}"
                      </p>
                    </div>

                    <p className="text-xs text-gray-600 leading-relaxed line-clamp-3 font-medium">
                      {template.summary}
                    </p>

                    {/* Economics & Certs */}
                    <div className="pt-2 border-t border-gray-100 grid grid-cols-2 gap-3 text-[11px]">
                      <div className="bg-gray-50 p-2.5 rounded-xl">
                        <span className="text-[9px] font-bold text-gray-400 uppercase tracking-widest block">Startup Est.</span>
                        <span className="font-black text-gray-900">{template.startupCostEst}</span>
                      </div>
                      <div className="bg-emerald-50/70 p-2.5 rounded-xl border border-emerald-100/50">
                        <span className="text-[9px] font-bold text-emerald-700 uppercase tracking-widest block">Gross Margin</span>
                        <span className="font-black text-emerald-900">{template.projectedMargin}</span>
                      </div>
                    </div>

                    {/* Certifications tags */}
                    <div className="flex flex-wrap gap-1.5 pt-1">
                      {template.keyCertifications.map((cert, idx) => (
                        <span key={idx} className="px-2 py-0.5 bg-gray-100 text-gray-600 rounded text-[9px] font-bold">
                          {cert}
                        </span>
                      ))}
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="space-y-2 pt-2">
                    <button
                      onClick={() => handleInstantViewPlan(template)}
                      className="w-full py-2.5 bg-emerald-900 hover:bg-emerald-800 text-white rounded-xl text-xs font-black uppercase tracking-wider flex items-center justify-center gap-2 transition-all shadow-sm active:scale-95"
                    >
                      <Sparkles className="w-3.5 h-3.5 text-emerald-300" />
                      Instant View Full Plan
                    </button>
                    <button
                      onClick={() => handleApplyTemplateToForm(template)}
                      className="w-full py-2 bg-gray-50 hover:bg-emerald-50 text-gray-700 hover:text-emerald-800 border border-gray-200 hover:border-emerald-200 rounded-xl text-[11px] font-black uppercase tracking-wider flex items-center justify-center gap-1.5 transition-all"
                    >
                      <Rocket className="w-3 h-3" />
                      Load into AI Generator
                    </button>
                  </div>
                </div>
              ))}
            </div>

            {filteredTemplates.length === 0 && (
              <div className="p-12 text-center bg-gray-50 rounded-3xl border border-gray-200 space-y-4">
                <Search className="w-8 h-8 text-gray-400 mx-auto" />
                <p className="text-sm font-bold text-gray-600">No templates found matching "{searchQuery}".</p>
                <button
                  onClick={() => { setSearchQuery(""); setSelectedCategory("All"); }}
                  className="px-4 py-2 bg-emerald-800 text-white rounded-xl text-xs font-bold uppercase tracking-wider"
                >
                  Clear Filters
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

